/**
 * Bundles dist/server/server.js into api/ssr.js so Vercel
 * includes all server code in the serverless function bundle.
 */
import { build } from 'esbuild';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

await build({
  entryPoints: [resolve(root, 'dist/server/server.js')],
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',
  outfile: resolve(root, 'api/ssr.js'),
  allowOverwrite: true,
  // Inline everything — no external deps at runtime
  packages: 'bundle',
  banner: {
    js: '// Auto-generated by scripts/build-api.mjs — do not edit',
  },
});

console.log('✓ api/ssr.js bundled successfully');
