// This file is auto-generated by scripts/build-api.mjs during build.
// It will be replaced with the bundled SSR server before deployment.
// Do not edit manually.
export default function handler(req, res) {
  res.status(503).send('Build in progress');
}
